import Head from "next/head";
import Image from "next/image";
import Good from "../components/Good";
import { ContainerStyled } from "../components/styles/ContainerStyled";
import { season3 } from "../data/contestants";
import { ImageContainer } from "../components/styles/ImageContainer";
import { ContestantContainer } from "../components/styles/ContestantContainer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>XQC MASTERCHEF TIERLIST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ContainerStyled>
        {season3.map((c) => (
          <ContestantContainer key={c.id}>
            <ImageContainer>
              <Image src={c.img} layout="fill" />
            </ImageContainer>
            <p>{c.name}</p>
          </ContestantContainer>
        ))}
      </ContainerStyled> */}
    </div>
  );
}
