import Head from "next/head";
import Image from "next/image";
import Good from "../components/Good";
import { ContainerStyled } from "../components/styles/ContainerStyled";

export default function Home() {
  return (
    <div>
      <Head>
        <title>XQC MASTERCHEF TIERLIST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
